export const ADD_USER_ACCOUNT_REQUEST = "ADD_USER_ACCOUNT_REQUEST";
export const ADD_USER_ACCOUNT_SUCCESS = "ADD_USER_ACCOUNT_SUCCESS";
export const ADD_USER_ACCOUNT_ERROR = "ADD_USER_ACCOUNT_ERROR";

export const LOGIN_USER_ACCOUNT_REQUEST = "LOGIN_USER_ACCOUNT_REQUEST";
export const LOGIN_USER_ACCOUNT_SUCCESS = "LOGIN_USER_ACCOUNT_SUCCESS";
export const LOGIN_USER_ACCOUNT_ERROR = "LOGIN_USER_ACCOUNT_ERROR";

export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD_REQUEST";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_ERROR = "IMAGE_UPLOAD_ERROR";
export const IMAGE_UPLOAD_RESET = "IMAGE_UPLOAD_RESET";

export const DELETE_USER = "DELETE_USER";
export const ADMINPRODUCTS = "ADMINPRODUCTS";
export const DELETEADMINPRODUCT = "DELETEADMINPRODUCT"

export const LOGIN = "LOGIN"
export const PARENT = "PARENT"
export const SALES = "SALES"

export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE"
