export const ADD_USER_ACCOUNT_REQUEST = "ADD_USER_ACCOUNT_REQUEST";
export const ADD_USER_ACCOUNT_SUCCESS = "ADD_USER_ACCOUNT_SUCCESS";
export const ADD_USER_ACCOUNT_ERROR = "ADD_USER_ACCOUNT_ERROR";

export const LOGIN_USER_ACCOUNT_REQUEST = "LOGIN_USER_ACCOUNT_REQUEST";
export const LOGIN_USER_ACCOUNT_SUCCESS = "LOGIN_USER_ACCOUNT_SUCCESS";
export const LOGIN_USER_ACCOUNT_ERROR = "LOGIN_USER_ACCOUNT_ERROR";

export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD_REQUEST";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_ERROR = "IMAGE_UPLOAD_ERROR";
export const IMAGE_UPLOAD_RESET = "IMAGE_UPLOAD_RESET";

export const STORE_URL_REQUEST = "STORE_URL_REQUEST";
export const STORE_URL_SUCCESS = "STORE_URL_SUCCESS";
export const STORE_URL_ERROR = "STORE_URL_ERROR";

export const VIDEO_UPLOAD_REQUEST = "VIDEO_UPLOAD_REQUEST";
export const VIDEO_UPLOAD_SUCCESS = "VIDEO_UPLOAD_SUCCESS";
export const VIDEO_UPLOAD_ERROR = "VIDEO_UPLOAD_ERROR";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_ERROR = "NEW_PRODUCT_ERROR";

export const NEW_PRODUCT_SELECT_REQUEST = "NEW_PRODUCT_SELECT_REQUEST";
export const NEW_PRODUCT_SELECT_SUCCESS = "NEW_PRODUCT_SELECT_SUCCESS";
export const NEW_PRODUCT_SELECT_ERROR = "NEW_PRODUCT_SELECT_ERROR";

export const CREATE_STORE_REQUEST = "CREATE_STORE_REQUEST";
export const CREATE_STORE_SUCCESS = "CREATE_STORE_SUCCESS";
export const CREATE_STORE_ERROR = "CREATE_STORE_ERROR";

export const GET_STORES_REQUEST = "GET_STORES_REQUEST";
export const GET_STORES_SUCCESS = "GET_STORES_SUCCESS";
export const GET_STORES_ERROR = "GET_STORES_ERROR";

export const DELETE_STORE_BY_ID_REQUEST = "DELETE_STORE_BY_ID_REQUEST";
export const DELETE_STORE_BY_ID_SUCCESS = "DELETE_STORE_BY_ID_SUCCESS";
export const DELETE_STORE_BY_ID_ERROR = "DELETE_STORE_BY_ID_ERROR";

export const SETUP_SUCCESS_REQUEST = "SETUP_SUCCESS_REQUEST";
export const SETUP_SUCCESS_SUCCESS = "SETUP_SUCCESS_SUCCESS";
export const SETUP_SUCCESS_ERROR = "SETUP_SUCCESS_ERROR";

export const SEARCH_STORE_URL_REQUEST = "SEARCH_STORE_URL_REQUEST";
export const SEARCH_STORE_URL_SUCCESS = "SEARCH_STORE_URL_SUCCESS";
export const SEARCH_STORE_URL_ERROR = "SEARCH_STORE_URL_ERROR";

export const ADD_USER_PRODUCTS_REQUEST = "ADD_USER_PRODUCTS_REQUEST";
export const ADD_USER_PRODUCTS_SUCCESS = "ADD_USER_PRODUCTS_SUCCESS";
export const ADD_USER_PRODUCTS_ERROR = "ADD_USER_PRODUCTS_ERROR";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";


export const DELETE_USER_PRODUCTS_REQUEST = "DELETE_USER_PRODUCTS_REQUEST";
export const DELETE_USER_PRODUCTS_SUCCESS = "DELETE_USER_PRODUCTS_SUCCESS";
export const DELETE_USER_PRODUCTS_ERROR = "DELETE_USER_PRODUCTS_ERROR";

export const GET_TEAM_REQUEST = "GET_TEAM_REQUEST";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_ERROR = "GET_TEAM_ERROR";

export const USER_STORE = "USER_STORE";

export const GET_ALL_MEDIA_OF_USER_REQUEST = "GET_ALL_MEDIA_OF_USER_REQUEST";
export const GET_ALL_MEDIA_OF_USER_SUCCESS = "GET_ALL_MEDIA_OF_USER_SUCCESS";
export const GET_ALL_MEDIA_OF_USER_ERROR = "GET_ALL_MEDIA_OF_USER_ERROR";

export const GET_ONE_MEDIA_OF_USER_REQUEST = "GET_ONE_MEDIA_OF_USER_REQUEST";
export const GET_ONE_MEDIA_OF_USER_SUCCESS = "GET_ONE_MEDIA_OF_USER_SUCCESS";
export const GET_ONE_MEDIA_OF_USER_ERROR = "GET_ONE_MEDIA_OF_USER_ERROR";

export const UPDATE_MEDIA_OF_USER_REQUEST = "UPDATE_MEDIA_OF_USER_REQUEST";
export const UPDATE_MEDIA_OF_USER_SUCCESS = "UPDATE_MEDIA_OF_USER_SUCCESS";
export const UPDATE_MEDIA_OF_USER_ERROR = "UPDATE_MEDIA_OF_USER_ERROR";

export const ADD_OR_REMOVE_CHILD_PRODUCT_REQUEST = "ADD_OR_REMOVE_CHILD_PRODUCT_REQUEST";
export const ADD_OR_REMOVE_CHILD_PRODUCT_SUCCESS = "ADD_OR_REMOVE_CHILD_PRODUCT_SUCCESS";
export const ADD_OR_REMOVE_CHILD_PRODUCT_ERROR = "ADD_OR_REMOVE_CHILD_PRODUCT_ERROR";

export const DELETE_USER_PRODUCT_REQUEST = "DELETE_USER_PRODUCT_REQUEST";
export const DELETE_USER_PRODUCT_SUCCESS = "DELETE_USER_PRODUCT_SUCCESS";
export const DELETE_USER_PRODUCT_ERROR = "DELETE_USER_PRODUCT_ERROR";

export const GET_PRODUCTS_BY_ID_REQUEST = "GET_PRODUCTS_BY_ID_REQUEST";
export const GET_PRODUCTS_BY_ID_SUCCESS = "GET_PRODUCTS_BY_ID_SUCCESS";
export const GET_PRODUCTS_BY_ID_ERROR = "GET_PRODUCTS_BY_ID_ERROR";

export const SET_INTRO_VIDEO_REQUEST = "SET_INTRO_VIDEO_REQUEST";
export const SET_INTRO_VIDEO_SUCCESS = "SET_INTRO_VIDEO_SUCCESS";
export const SET_INTRO_VIDEO_ERROR = "SET_INTRO_VIDEO_ERROR";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

export const MYSALES_REQUEST = "MYSALES_REQUEST";
export const MYSALES_SUCCESS = "MYSALES_SUCCESS";
export const MYSALES_ERROR = "MYSALES_ERROR";

export const TOTALSALES_REQUEST = "TOTALSALES_REQUEST";
export const TOTALSALES_SUCCESS = "TOTALSALES_SUCCESS";
export const TOTALSALES_ERROR = "TOTALSALES_ERROR";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const SLMSALES_REQUEST = "SLMSALES_REQUEST";
export const SLMSALES_SUCCESS = "SLMSALES_SUCCESS";
export const SLMSALES_ERROR = "SLMSALES_ERROR";
export const PACKAGES = "PACKAGES";
export const TRANSACTION = "TRANSACTION";

export const TOKEN_VERIFY_REQUEST = "TOKEN_VERIFY_REQUEST";
export const TOKEN_VERIFY_SUCCESS = "TOKEN_VERIFY_SUCCESS";
export const TOKEN_VERIFY_ERROR = "TOKEN_VERIFY_ERROR";

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_ERROR = "ADMIN_LOGIN_ERROR";

export const ADMIN_TOKEN_VALIDATE_REQUEST = "ADMIN_TOKEN_VALIDATE_REQUEST";
export const ADMIN_TOKEN_VALIDATE_SUCCESS = "ADMIN_TOKEN_VALIDATE_SUCCESS";
export const ADMIN_TOKEN_VALIDATE_ERROR = "ADMIN_TOKEN_VALIDATE_ERROR";

export const USER_TRANSACTION_REQUEST = "USER_TRANSACTION_REQUEST";
export const USER_TRANSACTION_SUCCESS = "USER_TRANSACTION_SUCCESS";
export const USER_TRANSACTION_ERROR = "USER_TRANSACTION_ERROR";

export const USER_ACCOUNT_STATS_REQUEST = "USER_ACCOUNT_STATS_REQUEST";
export const USER_ACCOUNT_STATS_SUCCESS = "USER_ACCOUNT_STATS_SUCCESS";
export const USER_ACCOUNT_STATS_ERROR = "USER_ACCOUNT_STATS_ERROR";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";

export const DELETE_USER = "DELETE_USER";
export const ADMINPRODUCTS = "ADMINPRODUCTS";
export const DELETEADMINPRODUCT = "DELETEADMINPRODUCT"

export const LOGIN = "LOGIN"
export const PARENT = "PARENT"
export const SALES = "SALES"

export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE"
